FROM tadeorubio/pyodbc-msodbcsql17

# copy the requirements file into the image
COPY ./Baza/Napolni/requirements.txt /DB/requirements.txt

# switch working directory
WORKDIR /DB

RUN pip install --upgrade pip
# install the dependencies and packages in the requirements file
RUN pip install -r requirements.txt

# copy every content from the local file to the image
COPY . /DB
# configure the container to run in an executed manner
ENTRYPOINT [ "python" ]

CMD ["./Baza/Napolni/python_script.py", "Database", "1433", "SA", "yourStrong(!)Password", "base123", "setup.sql"]