apiVersion: apps/v1
kind: Deployment
metadata:
  name: katalog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: katalog
  template:
    metadata:
      labels:
        app: katalog
    spec:
      containers:
        - image: tito1234/primerjalnik_cen:Katalog2022-12-02-18-24-31
          name: katalog
          
          ports:
            - containerPort: 5000
              name: server
              protocol: TCP

        - image: tito1234/primerjalnik_cen:DBUstvari2022-12-03-05-48-00
          name: bazaustvari
          ports:
            - containerPort: 1433
              name: baza
              protocol: TCP

        - image: tito1234/primerjalnik_cen:DBNapolni2022-12-03-05-48-00
          name: bazanapolni
          ports:
            - containerPort: 1433
              name: baza
              protocol: TCP

---

apiVersion: v1
kind: Service
metadata:
  name: balancer
spec:
  type: LoadBalancer
  ports:
    - port: 5000
      protocol: TCP
      targetPort: server
  selector:
    app: katalog