apiVersion: apps/v1
kind: Deployment
metadata:
  name: image-catalog-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: Katalog
  template:
    metadata:
      labels:
        app: Katalog
    spec:
      containers:
        - image: tito1234/primerjalnik_cen:Katalog:latest
          name: Katalog
          env:
            - name: KUMULUZEE_DATASOURCES0_CONNECTIONURL
              value: jdbc:postgresql://fanny.db.elephantsql.com:5432/zqjqqtrd
            - name: KUMULUZEE_DATASOURCES0_USERNAME
              value: zqjqqtrd
            - name: KUMULUZEE_DATASOURCES0_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pg-pass
                  key: KUMULUZEE_DATASOURCES0_PASSWORD
          ports:
            - containerPort: 5000
              name: server
              protocol: TCP

---

apiVersion: v1
kind: Service
metadata:
  name: Katalog
spec:
  type: LoadBalancer
  ports:
    - port: 5000
      protocol: TCP
      targetPort: server
  selector:
    app: Katalog