apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: appspletnivmesnik
  name: appspletnivmesnik
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: appspletnivmesnik
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: appspletnivmesnik
    spec:
      containers:
        - image: tito1234/primerjalnik_cen:SpletniVmesnik
          name: appspletnivmesnik
          ports:
            - containerPort: 5004
          resources: {}
      restartPolicy: Always
status: {}
