name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: Get Time
        id: time
        uses: nanzm/get-time-action@v1.0
        with:
         timeZone: 1
         format: 'YYYY-MM-DD-HH-mm-ss'
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Build and Push the Docker image Katalog1
        uses: docker/build-push-action@v3
        with:
          file: ./Katalog/Dockerfile
          push: true
          tags: tito1234/primerjalnik_cen:Katalog
      - name: Build and Push the Docker image Uporabnik
        uses: docker/build-push-action@v3
        with:
          file: ./Uporabnik/Dockerfile
          push: true
          tags: tito1234/primerjalnik_cen:Uporabnik
          
      - name: Build and Push the Docker image Kosarica
        uses: docker/build-push-action@v3
        with:
          file: ./Kosarica/Dockerfile
          push: true
          tags: tito1234/primerjalnik_cen:Kosarica

      - name: Build and Push the Docker image PrimerjavaCen
        uses: docker/build-push-action@v3
        with:
          file: ./PrimerjavaCen/Dockerfile
          push: true
          tags: tito1234/primerjalnik_cen:PrimerjavaCen
          
      - name: Build and Push the Docker image SpletniVmesnik
        uses: docker/build-push-action@v3
        with:
          file: ./SpletniVmesnik/Dockerfile
          push: true
          tags: tito1234/primerjalnik_cen:SpletniVmesnik
          
      - name: Build and Push the Docker image PridobivanjePodatkov
        uses: docker/build-push-action@v3
        with:
          file: ./PridobivanjePodatkov/Dockerfile
          push: true
          tags: tito1234/primerjalnik_cen:PridobivanjePodatkov

