name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./Katalog

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      uses: docker/build-push-action@v2
      with:
        file: Dockerfile
        push: true
        tags: jozaizgozda/primerjalnik_cen


